"""add higherIsBetter to academic_indicator

Revision ID: a96268e34773
Revises: d06a594fe27c
Create Date: 2026-08-16 18:01:46.380251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96268e34773'
down_revision: Union[str, Sequence[str], None] = 'd06a594fe27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_indicators', sa.Column('higherIsBetter', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_indicators', 'higherIsBetter')
    # ### end Alembic commands ###
