"""create initial 16 tables

Revision ID: d06a594fe27c
Revises: 
Create Date: 2026-08-16 03:03:16.897356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06a594fe27c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_indicators',
    sa.Column('indicatorID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('dataType', sa.String(length=20), nullable=False),
    sa.Column('minValue', sa.Float(), nullable=False),
    sa.Column('maxValue', sa.Float(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('indicatorID'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_academic_indicators_indicatorID'), 'academic_indicators', ['indicatorID'], unique=False)
    op.create_table('modules',
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('moduleCode', sa.String(length=20), nullable=False),
    sa.Column('moduleName', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('moduleID')
    )
    op.create_index(op.f('ix_modules_moduleCode'), 'modules', ['moduleCode'], unique=True)
    op.create_index(op.f('ix_modules_moduleID'), 'modules', ['moduleID'], unique=False)
    op.create_table('students',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('studentNumber', sa.String(length=20), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_index(op.f('ix_students_studentID'), 'students', ['studentID'], unique=False)
    op.create_index(op.f('ix_students_studentNumber'), 'students', ['studentNumber'], unique=True)
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Lecturer', name='userrole'), nullable=False),
    sa.Column('staffNumber', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_table('audit_logs',
    sa.Column('logID', sa.Integer(), nullable=False),
    sa.Column('eventType', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('targetEntity', sa.String(length=50), nullable=True),
    sa.Column('targetID', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('logID')
    )
    op.create_index(op.f('ix_audit_logs_logID'), 'audit_logs', ['logID'], unique=False)
    op.create_table('configuration_history',
    sa.Column('historyID', sa.Integer(), nullable=False),
    sa.Column('configType', sa.String(length=30), nullable=False),
    sa.Column('referenceID', sa.Integer(), nullable=False),
    sa.Column('oldValue', sa.String(length=100), nullable=True),
    sa.Column('newValue', sa.String(length=100), nullable=True),
    sa.Column('changedBy', sa.Integer(), nullable=True),
    sa.Column('changedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('historyID')
    )
    op.create_index(op.f('ix_configuration_history_historyID'), 'configuration_history', ['historyID'], unique=False)
    op.create_table('csv_uploads',
    sa.Column('uploadID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recordCount', sa.Integer(), nullable=False),
    sa.Column('uploadedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lecturerID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['moduleID'], ['modules.moduleID'], ),
    sa.PrimaryKeyConstraint('uploadID')
    )
    op.create_index(op.f('ix_csv_uploads_uploadID'), 'csv_uploads', ['uploadID'], unique=False)
    op.create_table('enrollments',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['moduleID'], ['modules.moduleID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('studentID', 'moduleID')
    )
    op.create_table('health_reports',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('uptime', sa.Float(), nullable=False),
    sa.Column('avgResponseTime', sa.Float(), nullable=False),
    sa.Column('errorRate', sa.Float(), nullable=False),
    sa.Column('flaggedIssues', sa.Text(), nullable=True),
    sa.Column('generatedBy', sa.Integer(), nullable=False),
    sa.Column('generatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generatedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('reportID')
    )
    op.create_index(op.f('ix_health_reports_reportID'), 'health_reports', ['reportID'], unique=False)
    op.create_table('intervention_notes',
    sa.Column('interventionID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.Column('interventionType', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('followUpDate', sa.Date(), nullable=True),
    sa.Column('contextNote', sa.Text(), nullable=True),
    sa.Column('riskLabelAtTime', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcomeNote', sa.Text(), nullable=True),
    sa.Column('resolvedBy', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lecturerID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['resolvedBy'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('interventionID')
    )
    op.create_index(op.f('ix_intervention_notes_interventionID'), 'intervention_notes', ['interventionID'], unique=False)
    op.create_table('lecturer_modules',
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('assignedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lecturerID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['moduleID'], ['modules.moduleID'], ),
    sa.PrimaryKeyConstraint('lecturerID', 'moduleID')
    )
    op.create_table('scoring_weights',
    sa.Column('weightID', sa.Integer(), nullable=False),
    sa.Column('indicatorID', sa.Integer(), nullable=False),
    sa.Column('weightValue', sa.Float(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['indicatorID'], ['academic_indicators.indicatorID'], ),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('weightID'),
    sa.UniqueConstraint('indicatorID')
    )
    op.create_index(op.f('ix_scoring_weights_weightID'), 'scoring_weights', ['weightID'], unique=False)
    op.create_table('threshold_configurations',
    sa.Column('thresholdID', sa.Integer(), nullable=False),
    sa.Column('lowMax', sa.Float(), nullable=False),
    sa.Column('mediumMax', sa.Float(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('thresholdID')
    )
    op.create_index(op.f('ix_threshold_configurations_thresholdID'), 'threshold_configurations', ['thresholdID'], unique=False)
    op.create_table('academic_records',
    sa.Column('recordID', sa.Integer(), nullable=False),
    sa.Column('uploadID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('indicatorID', sa.Integer(), nullable=False),
    sa.Column('rawValue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['indicatorID'], ['academic_indicators.indicatorID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.ForeignKeyConstraint(['uploadID'], ['csv_uploads.uploadID'], ),
    sa.PrimaryKeyConstraint('recordID')
    )
    op.create_index(op.f('ix_academic_records_recordID'), 'academic_records', ['recordID'], unique=False)
    op.create_table('risk_scores',
    sa.Column('riskScoreID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('uploadID', sa.Integer(), nullable=False),
    sa.Column('totalScore', sa.Float(), nullable=False),
    sa.Column('riskLabel', sa.String(length=10), nullable=False),
    sa.Column('isPartial', sa.Boolean(), nullable=False),
    sa.Column('computedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['moduleID'], ['modules.moduleID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.ForeignKeyConstraint(['uploadID'], ['csv_uploads.uploadID'], ),
    sa.PrimaryKeyConstraint('riskScoreID')
    )
    op.create_index(op.f('ix_risk_scores_riskScoreID'), 'risk_scores', ['riskScoreID'], unique=False)
    op.create_table('risk_contributions',
    sa.Column('contributionID', sa.Integer(), nullable=False),
    sa.Column('riskScoreID', sa.Integer(), nullable=False),
    sa.Column('indicatorID', sa.Integer(), nullable=False),
    sa.Column('rawValue', sa.Float(), nullable=False),
    sa.Column('weightApplied', sa.Float(), nullable=False),
    sa.Column('weightedContribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['indicatorID'], ['academic_indicators.indicatorID'], ),
    sa.ForeignKeyConstraint(['riskScoreID'], ['risk_scores.riskScoreID'], ),
    sa.PrimaryKeyConstraint('contributionID')
    )
    op.create_index(op.f('ix_risk_contributions_contributionID'), 'risk_contributions', ['contributionID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_contributions_contributionID'), table_name='risk_contributions')
    op.drop_table('risk_contributions')
    op.drop_index(op.f('ix_risk_scores_riskScoreID'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_academic_records_recordID'), table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_threshold_configurations_thresholdID'), table_name='threshold_configurations')
    op.drop_table('threshold_configurations')
    op.drop_index(op.f('ix_scoring_weights_weightID'), table_name='scoring_weights')
    op.drop_table('scoring_weights')
    op.drop_table('lecturer_modules')
    op.drop_index(op.f('ix_intervention_notes_interventionID'), table_name='intervention_notes')
    op.drop_table('intervention_notes')
    op.drop_index(op.f('ix_health_reports_reportID'), table_name='health_reports')
    op.drop_table('health_reports')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_csv_uploads_uploadID'), table_name='csv_uploads')
    op.drop_table('csv_uploads')
    op.drop_index(op.f('ix_configuration_history_historyID'), table_name='configuration_history')
    op.drop_table('configuration_history')
    op.drop_index(op.f('ix_audit_logs_logID'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_studentNumber'), table_name='students')
    op.drop_index(op.f('ix_students_studentID'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_modules_moduleID'), table_name='modules')
    op.drop_index(op.f('ix_modules_moduleCode'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_academic_indicators_indicatorID'), table_name='academic_indicators')
    op.drop_table('academic_indicators')
    # ### end Alembic commands ###
