from app.models.user import User
from app.models.module import Module
from app.models.student import Student
from app.models.lecturer_module import LecturerModule
from app.models.enrollment import Enrollment
from app.models.academic_indicator import AcademicIndicator
from app.models.scoring_weight import ScoringWeight
from app.models.threshold_configuration import ThresholdConfiguration
from app.models.configuration_history import ConfigurationHistory
from app.models.csv_upload import CSVUpload
from app.models.academic_record import AcademicRecord
from app.models.risk_score import RiskScore
from app.models.risk_contribution import RiskContribution
from app.models.intervention_note import InterventionNote
from app.models.audit_log import AuditLog
from app.models.health_report import HealthReport